# Generated by Django 2.0.5 on 2020-03-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crontask',
            old_name='end_time',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='crontask',
            old_name='start_time',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='tasklog',
            old_name='end_time',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='tasklog',
            old_name='start_time',
            new_name='start_date',
        ),
    ]
