# Generated by Django 2.0.5 on 2020-03-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0002_auto_20200325_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklog',
            old_name='next_time',
            new_name='next_run_time',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='run_time',
        ),
        migrations.AddField(
            model_name='tasklog',
            name='duration',
            field=models.CharField(max_length=128, null=True, verbose_name='执行一次耗时'),
        ),
    ]
