# Generated by Django 2.0.5 on 2020-03-25 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0003_auto_20200325_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklog',
            old_name='task_id',
            new_name='task',
        ),
    ]
