# Generated by Django 2.0.5 on 2020-03-25 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0005_auto_20200325_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crontask',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='task_name',
        ),
    ]
