# Generated by Django 2.0.5 on 2020-03-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0006_auto_20200325_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='crontask',
            name='interval',
            field=models.PositiveIntegerField(null=True, verbose_name='间隔时间'),
        ),
        migrations.AddField(
            model_name='crontask',
            name='name',
            field=models.CharField(max_length=256, null=True, verbose_name='任务名称'),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='task_name',
            field=models.CharField(max_length=256, null=True, verbose_name='任务名称'),
        ),
    ]
